import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: "#f9f9f9",
        "surface-container-low": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#323232",
        "on-surface-variant": "#5f5f5f",
        "inverse-surface": "#0e0e0e",
        "inverse-on-surface": "#9d9d9d",
        primary: "#5e5e5e",
        "on-primary": "#f8f8f8",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#525252",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#d4d4d4",
        secondary: "#5f5f5f",
        "on-secondary": "#fbf8f8",
        "secondary-container": "#e4e2e2",
        "on-secondary-container": "#525152",
        "secondary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#d6d4d4",
        tertiary: "#9e2b9c",
        "on-tertiary": "#fff7f9",
        "tertiary-container": "#ff82f5",
        "on-tertiary-container": "#5b005b",
        "tertiary-fixed": "#ff82f5",
        "tertiary-fixed-dim": "#ef74e6",
        error: "#9e3f4e",
        "on-error": "#fff7f7",
        "error-container": "#ff8b9a",
        "on-error-container": "#782232",
        outline: "#7b7b7b",
        "outline-variant": "#b2b2b2",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#5e5e5e",
        "surface-container": "#eeeeee",
        "purple-accent": "#800080",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;